import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# A wide array of symbols to satisfy the request
SYMBOLS = [
    "A",
    "AA",
    "AAP",
    "AAPL",
    "ABBV",
    "ABG",
    "ABNB",
    "ABT",
    "ACHC",
    "ACM",
    "ACV",
    "ADBE",
    "ADI",
    "ADM",
    "ADUS",
    "AEM",
    "AEO",
    "AEP",
    "AES",
    "AFG",
    "AFI",
    "AFL",
    "AFRM",
    "AGCO",
    "AGG",
    "AGNC",
    "AGRO",
    "AJG",
    "AKAM",
    "ALCO",
    "ALGN",
    "ALHC",
    "ALHE",
    "ALL",
    "ALLE",
    "ALLY",
    "ALNY",
    "ALST",
    "ALTM",
    "ALUM",
    "AMAT",
    "AMCR",
    "AMD",
    "AME",
    "AMED",
    "AMG",
    "AMGN",
    "AMH",
    "AMOT",
    "AMP",
    "AMRX",
    "AMT",
    "AMZN",
    "AN",
    "ANDE",
    "ANF",
    "ANSS",
    "AON",
    "AOS",
    "APA",
    "APAM",
    "APO",
    "ARAD",
    "ARE",
    "ARES",
    "ARGO",
    "ASML",
    "ASYS",
    "AUD",
    "AUDC",
    "AVB",
    "AVDX",
    "AVGO",
    "AVY",
    "AXP",
    "AY",
    "AYAL",
    "AZO",
    "AZRG",
    "AZRI",
    "BA",
    "BABA",
    "BAC",
    "BAM",
    "BANR",
    "BARK",
    "BAX",
    "BC",
    "BCC",
    "BCS",
    "BDX",
    "BE",
    "BEN",
    "BEP",
    "BERY",
    "BESH",
    "BG",
    "BHF",
    "BHP",
    "BIE",
    "BIG",
    "BIIB",
    "BILL",
    "BJ",
    "BK",
    "BKNG",
    "BKR",
    "BLDP",
    "BLK",
    "BLL",
    "BMY",
    "BND",
    "BNTX",
    "BOC",
    "BOKF",
    "BOX",
    "BP",
    "BREN",
    "BRK.B",
    "BRO",
    "BRX",
    "BSX",
    "BTI",
    "BUD",
    "BURL",
    "BX",
    "BXMT",
    "BXP",
    "BYD",
    "C",
    "CACC",
    "CAD",
    "CAG",
    "CAMT",
    "CAST",
    "CAT",
    "CB",
    "CBL",
    "CBOE",
    "CBRE",
    "CBU",
    "CCI",
    "CCK",
    "CCS",
    "CDE",
    "CE",
    "CEG",
    "CEL",
    "CELH",
    "CENX",
    "CERT",
    "CF",
    "CFG",
    "CFR",
    "CG",
    "CGA",
    "CHD",
    "CHDN",
    "CHEF",
    "CHF",
    "CHH",
    "CHKP",
    "CHMI",
    "CHRW",
    "CHTR",
    "CHWY",
    "CI",
    "CIEN",
    "CIM",
    "CINF",
    "CL",
    "CL=F",
    "CLAL",
    "CLOV",
    "CLR",
    "CLX",
    "CMA",
    "CMC",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CNC",
    "CNHI",
    "CNI",
    "CNP",
    "CNSL",
    "CNY",
    "COF",
    "COGN",
    "COHR",
    "COIN",
    "COLD",
    "COMP",
    "CONE",
    "COO",
    "COP",
    "COR",
    "CORE",
    "COST",
    "COTY",
    "CP",
    "CPB",
    "CPNG",
    "CPRI",
    "CPT",
    "CRBG",
    "CRL",
    "CRM",
    "CROX",
    "CRSP",
    "CRWD",
    "CRX",
    "CS",
    "CSCO",
    "CSIQ",
    "CSX",
    "CTRA",
    "CTVA",
    "CURO",
    "CUZ",
    "CVBF",
    "CVET",
    "CVI",
    "CVS",
    "CVX",
    "CWEN",
    "CWK",
    "CX",
    "CXP",
    "CYBR",
    "CYH",
    "CZR",
    "D",
    "D-WAVE",
    "DAC",
    "DAR",
    "DATA",
    "DB",
    "DBC",
    "DBX",
    "DD",
    "DDD",
    "DDOG",
    "DE",
    "DEI",
    "DELTA",
    "DFS",
    "DG",
    "DHI",
    "DHR",
    "DIA",
    "DINO",
    "DIS",
    "DISI",
    "DK",
    "DKNG",
    "DLEI",
    "DLR",
    "DLTR",
    "DM",
    "DOC",
    "DOCS",
    "DOCU",
    "DOLE",
    "DOV",
    "DOW",
    "DPZ",
    "DRE",
    "DRI",
    "DUK",
    "DVN",
    "DXC",
    "EARN",
    "EBAY",
    "EBS",
    "ECL",
    "ECP",
    "ECPG",
    "ED",
    "EDIT",
    "EDR",
    "EDRI",
    "EEM",
    "EFA",
    "EG",
    "EGLE",
    "EGP",
    "EHC",
    "EIG",
    "EIX",
    "EL",
    "ELAN",
    "ELCO",
    "ELECT",
    "ELF",
    "ELS",
    "ELV",
    "EMB",
    "EMN",
    "EMR",
    "ENB",
    "ENBL",
    "ENDP",
    "ENLT",
    "ENPH",
    "ENR",
    "ENVA",
    "ENVX",
    "EOG",
    "EPC",
    "EPD",
    "EQIX",
    "EQR",
    "ESLT",
    "ESS",
    "ET",
    "ETSY",
    "EUR",
    "EURN",
    "EURUSD=X",
    "EW",
    "EXAS",
    "EXC",
    "EXP",
    "EXPD",
    "EXPE",
    "EXPI",
    "EYE",
    "F",
    "FANG",
    "FAST",
    "FBHS",
    "FCEL",
    "FCX",
    "FDP",
    "FDS",
    "FDX",
    "FE",
    "FHN",
    "FIBI",
    "FIBK",
    "FITB",
    "FLYW",
    "FMC",
    "FNB",
    "FND",
    "FNKO",
    "FOR",
    "FOX",
    "FOXA",
    "FR",
    "FRO",
    "FRPT",
    "FRT",
    "FSLR",
    "FSLY",
    "FTI",
    "FTNT",
    "FVRR",
    "FYBR",
    "GBP",
    "GBPUSD=X",
    "GC=F",
    "GD",
    "GEF",
    "GFF",
    "GFS",
    "GGB",
    "GILD",
    "GIS",
    "GL",
    "GLD",
    "GLNCY",
    "GM",
    "GOGL",
    "GOLD",
    "GOLF",
    "GOOGL",
    "GPI",
    "GPK",
    "GPM",
    "GPRO",
    "GPS",
    "GRBK",
    "GS",
    "GSHD",
    "GTC",
    "GVA",
    "GWR",
    "H",
    "HAL",
    "HAMO",
    "HARL",
    "HAS",
    "HASI",
    "HBAN",
    "HBM",
    "HCA",
    "HD",
    "HDST",
    "HE",
    "HEI",
    "HELE",
    "HENKY",
    "HES",
    "HFFC",
    "HFM",
    "HFSI",
    "HG=F",
    "HII",
    "HL",
    "HLT",
    "HMC",
    "HOG",
    "HOMB",
    "HOOD",
    "HP",
    "HPAL",
    "HPP",
    "HQY",
    "HR",
    "HRL",
    "HSIC",
    "HSY",
    "HUI",
    "HUM",
    "HUN",
    "HYG",
    "HYSR",
    "HZNP",
    "HZO",
    "IAU",
    "IBM",
    "ICE",
    "ICL",
    "IDXX",
    "IEF",
    "IHG",
    "IJH",
    "IJR",
    "ILDC",
    "ILMN",
    "ILPT",
    "ILS",
    "ILS=X",
    "IMBBY",
    "INCY",
    "INTC",
    "INVH",
    "IONQ",
    "IP",
    "IPGP",
    "IPI",
    "IQV",
    "IRM",
    "ISPR",
    "ISRG",
    "ITW",
    "IVZ",
    "IWM",
    "JAZZ",
    "JBHT",
    "JHG",
    "JJSF",
    "JKS",
    "JLL",
    "JMIA",
    "JNJ",
    "JNPR",
    "JPM",
    "JPY",
    "JPY=X",
    "JRVR",
    "JTLV",
    "K",
    "KBH",
    "KDP",
    "KEN",
    "KEY",
    "KGC",
    "KHC",
    "KIM",
    "KINS",
    "KKR",
    "KLAC",
    "KMI",
    "KMPR",
    "KMX",
    "KNSL",
    "KNX",
    "KO",
    "KRC",
    "KRT",
    "KSU",
    "KTB",
    "LAD",
    "LCI",
    "LCID",
    "LEAD",
    "LEN",
    "LHX",
    "LI",
    "LITE",
    "LLY",
    "LMNR",
    "LMT",
    "LNC",
    "LOW",
    "LQD",
    "LRCX",
    "LSTR",
    "LTC",
    "LULU",
    "LUMI",
    "LUMN",
    "LVS",
    "LW",
    "LXU",
    "LYB",
    "LYV",
    "M",
    "MA",
    "MAA",
    "MAC",
    "MAR",
    "MAS",
    "MAT",
    "MATX",
    "MAXN",
    "MBII",
    "MCD",
    "MCHP",
    "MCO",
    "MDC",
    "MDGL",
    "MDRN",
    "MDT",
    "MED",
    "MEDP",
    "MELI",
    "MELSR",
    "MENA",
    "MET",
    "META",
    "MGDL",
    "MGM",
    "MGP",
    "MGRC",
    "MGS",
    "MHK",
    "MINT",
    "MITT",
    "MKL",
    "MKSI",
    "MLM",
    "MMC",
    "MMP",
    "MNDY",
    "MNR",
    "MNST",
    "MO",
    "MOH",
    "MORN",
    "MOS",
    "MPC",
    "MPLX",
    "MPW",
    "MQ",
    "MRK",
    "MRLN",
    "MRNA",
    "MRO",
    "MRVL",
    "MS",
    "MSCI",
    "MSFT",
    "MSM",
    "MT",
    "MTB",
    "MTD",
    "MTH",
    "MTW",
    "MU",
    "MUB",
    "MYE",
    "MZN",
    "NANO",
    "NAPA",
    "NATI",
    "NAVI",
    "NBR",
    "NDAQ",
    "NEE",
    "NEM",
    "NEP",
    "NET",
    "NFLX",
    "NHI",
    "NICE",
    "NIO",
    "NKE",
    "NLY",
    "NNDM",
    "NNN",
    "NOC",
    "NOV",
    "NOVA",
    "NOW",
    "NRG",
    "NSC",
    "NTAP",
    "NTLA",
    "NTR",
    "NTRS",
    "NUE",
    "NVDA",
    "NVO",
    "NVR",
    "NWL",
    "NWM",
    "NXPI",
    "O",
    "OAK",
    "ODFL",
    "OHI",
    "OI",
    "OII",
    "OKE",
    "OKTA",
    "OMCL",
    "OMF",
    "ONB",
    "ONT",
    "OPC",
    "OPEN",
    "ORAN",
    "ORC",
    "ORCL",
    "ORL",
    "ORLY",
    "ORMT",
    "OSCR",
    "OSK",
    "OVV",
    "OXY",
    "PAA",
    "PAAS",
    "PACW",
    "PAG",
    "PAHC",
    "PALL",
    "PANW",
    "PARA",
    "PARR",
    "PBCT",
    "PBF",
    "PCAR",
    "PCG",
    "PDCO",
    "PDY",
    "PEAK",
    "PEG",
    "PEI",
    "PENN",
    "PEP",
    "PERI",
    "PETS",
    "PFE",
    "PFG",
    "PFGC",
    "PFSW",
    "PG",
    "PGR",
    "PGRE",
    "PGY",
    "PH",
    "PHI",
    "PHM",
    "PHOE",
    "PHR",
    "PI",
    "PII",
    "PKG",
    "PKX",
    "PLAT",
    "PLD",
    "PLTR",
    "PLUG",
    "PM",
    "PNC",
    "PNW",
    "POLI",
    "PPG",
    "PPL",
    "PPLT",
    "PPRO",
    "PRAA",
    "PRGO",
    "PRLB",
    "PROV",
    "PRU",
    "PSTG",
    "PSX",
    "PTEN",
    "PTK",
    "PTNR",
    "PVH",
    "PVTL",
    "PWR",
    "PXD",
    "PYPL",
    "PZOL",
    "QBTS",
    "QCOM",
    "QLYS",
    "QQQ",
    "QSR",
    "QTS",
    "RADA",
    "RAMI",
    "RBGLY",
    "RCII",
    "RCM",
    "RDFN",
    "RDWR",
    "RE",
    "REG",
    "REGN",
    "REIT1",
    "REMY",
    "RETI",
    "REX",
    "RF",
    "RGA",
    "RGTI",
    "RICK",
    "RIG",
    "RIO",
    "RIVN",
    "RL",
    "RLX",
    "RM",
    "RNR",
    "ROK",
    "ROST",
    "RPD",
    "RRC",
    "RS",
    "RSI",
    "RTX",
    "RUN",
    "RUSHB",
    "RYAN",
    "SAH",
    "SAIA",
    "SAM",
    "SANF",
    "SBAC",
    "SBCF",
    "SBLK",
    "SBN",
    "SBRA",
    "SBUX",
    "SCCO",
    "SE",
    "SEDG",
    "SEE",
    "SEED",
    "SELA",
    "SEM",
    "SGC",
    "SGD",
    "SGEN",
    "SGOL",
    "SGRY",
    "SHAK",
    "SHEL",
    "SHFR",
    "SHLS",
    "SHW",
    "SHY",
    "SI=F",
    "SID",
    "SIG",
    "SIGI",
    "SILV",
    "SJM",
    "SJR",
    "SKX",
    "SLB",
    "SLG",
    "SLGN",
    "SLM",
    "SLV",
    "SMCI",
    "SMG",
    "SNA",
    "SNOW",
    "SNV",
    "SO",
    "SOFI",
    "SON",
    "SPB",
    "SPEN",
    "SPG",
    "SPGI",
    "SPLK",
    "SPNT",
    "SPTN",
    "SPWR",
    "SPY",
    "SQ",
    "SRE",
    "SSYS",
    "STAG",
    "STE",
    "STLA",
    "STLD",
    "STNG",
    "STRS",
    "STT",
    "STWD",
    "STX",
    "STZ",
    "SUI",
    "SUM",
    "SWK",
    "SWN",
    "SYF",
    "SYK",
    "SYY",
    "TAP",
    "TARO",
    "TASE",
    "TBI",
    "TCBI",
    "TCTR",
    "TDG",
    "TDOC",
    "TDS",
    "TEAM",
    "TECH",
    "TECK",
    "TER",
    "TEVA",
    "TEX",
    "TFC",
    "TGLS",
    "TGT",
    "THC",
    "THG",
    "THO",
    "TIP",
    "TJX",
    "TLT",
    "TM",
    "TMO",
    "TNDM",
    "TNK",
    "TNV",
    "TOL",
    "TOST",
    "TPB",
    "TPG",
    "TPR",
    "TR",
    "TRIP",
    "TRNO",
    "TROW",
    "TRP",
    "TRV",
    "TSCO",
    "TSLA",
    "TT",
    "TTE",
    "TWO",
    "TX",
    "TXN",
    "TXRH",
    "TXT",
    "UAA",
    "UAN",
    "UBS",
    "UDR",
    "UHS",
    "ULTA",
    "UMPQ",
    "UNFI",
    "UNH",
    "UNI",
    "UNIT",
    "UNM",
    "UNP",
    "UPS",
    "UPST",
    "URBN",
    "URI",
    "USB",
    "USCR",
    "USD",
    "USFD",
    "USM",
    "UTHR",
    "UVV",
    "V",
    "VALE",
    "VEA",
    "VEEV",
    "VFC",
    "VGR",
    "VLD",
    "VLO",
    "VMC",
    "VNO",
    "VOD",
    "VR",
    "VRT",
    "VRTX",
    "VSP",
    "VST",
    "VTR",
    "VTRS",
    "VWO",
    "WAL",
    "WAT",
    "WAY",
    "WBD",
    "WBS",
    "WCC",
    "WD40",
    "WDAY",
    "WDC",
    "WELL",
    "WEN",
    "WFC",
    "WGO",
    "WH",
    "WHR",
    "WIL",
    "WILG",
    "WIX",
    "WLK",
    "WMB",
    "WMG",
    "WMT",
    "WNR",
    "WOOF",
    "WRB",
    "WRK",
    "WSTG",
    "WTFC",
    "WTW",
    "WYNN",
    "XEL",
    "XOM",
    "XPEV",
    "XPO",
    "XRAY",
    "XXII",
    "XYL",
    "YETI",
    "YHND",
    "YTEN",
    "YUM",
    "Z",
    "ZBH",
    "ZEUS",
    "ZEVI",
    "ZIM",
    "ZINC",
    "ZION",
    "ZS",
    "ZTS"
]

def fetch_data(symbols, period="1y"):
    """
    Fetch historical close prices for the given symbols.
    Chunks the requests to avoid timeouts and cleanly drops unavailable tickers.
    """
    print(f"Fetching data for {len(symbols)} symbols over period: {period}...")
    chunk_size = 100
    all_data = []

    for i in range(0, len(symbols), chunk_size):
        chunk = symbols[i:i+chunk_size]
        print(f"Fetching chunk {i//chunk_size + 1}/{(len(symbols) + chunk_size - 1)//chunk_size}...")
        try:
            chunk_data = yf.download(chunk, period=period, progress=False, timeout=10)["Close"]
            if isinstance(chunk_data, pd.Series):
                chunk_data = chunk_data.to_frame(name=chunk[0])
            all_data.append(chunk_data)
        except Exception as e:
            print(f"Error fetching chunk: {e}")

    if not all_data:
        raise ValueError("Failed to fetch any data.")

    data = pd.concat(all_data, axis=1)

    # Handle potentially missing data: forward fill, then backward fill
    data = data.ffill().bfill()

    # Drop symbols that have entirely NaN values
    data = data.dropna(axis=1, how='all')
    print(f"Successfully fetched data for {data.shape[1]} symbols.")
    return data

def calculate_rsi(series, period=14):
    """Calculate Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_indicators(data):
    """
    Calculate moving averages, RSI, and continuous-time flow proxies (dh/dt)
    for each symbol to estimate 'real current price', momentum, and overbought/oversold conditions.
    """
    print("Calculating technical indicators & topological flow derivatives...")
    latest_prices = data.iloc[-1]

    # Instantaneous derivative proxy (dh/dt): 5-day velocity and 1-day tick velocity
    # Used to define the continuous-time momentum vector of the asset
    dh_dt_1d = data.pct_change(1).iloc[-1]
    dh_dt_5d = data.pct_change(5).iloc[-1]

    # Simple Moving Averages
    sma_50 = data.rolling(window=50).mean().iloc[-1]
    sma_200 = data.rolling(window=200).mean().iloc[-1]

    # Exponential Moving Averages
    ema_20 = data.ewm(span=20, adjust=False).mean().iloc[-1]

    # RSI
    rsi_14 = data.apply(calculate_rsi, period=14).iloc[-1]

    metrics = pd.DataFrame({
        'Current_Price': latest_prices,
        'dh_dt_1d': dh_dt_1d,
        'dh_dt_5d': dh_dt_5d,
        'SMA_50': sma_50,
        'SMA_200': sma_200,
        'EMA_20': ema_20,
        'RSI_14': rsi_14
    })

    # Mathematical meaning: distance from moving average (estimated real price)
    metrics['Dist_from_SMA_50_pct'] = ((metrics['Current_Price'] - metrics['SMA_50']) / metrics['SMA_50']) * 100
    metrics['Trend'] = np.where(metrics['Current_Price'] > metrics['SMA_50'], "Bullish (Above SMA50)", "Bearish (Below SMA50)")

    # Basic overbought/oversold logic
    conditions = [
        (metrics['RSI_14'] > 70),
        (metrics['RSI_14'] < 30)
    ]
    choices = ['Overbought', 'Oversold']
    metrics['RSI_Signal'] = np.select(conditions, choices, default='Neutral')

    return metrics

def perform_ml_analysis(data):
    """
    Use PCA and KMeans on daily returns to group symbols into 'learned sectors' in latent topological space.
    Constructs the Adjacency Matrix A(t) via correlation, and calculates Systemic Vaporization.
    """
    print("Performing ML analysis (Topological clustering & continuous diffusion)...")
    returns = data.pct_change().dropna()

    # 1. Adjacency Matrix A(t) - Continuous Price Correlation
    corr_matrix = returns.corr()

    # 2. Systemic Wealth Vaporization: Sum of system derivatives
    # If the total momentum of the closed loop is negative, liquidity is exiting.
    system_momentum_1d = returns.iloc[-1].sum()
    system_momentum_5d = returns.iloc[-5:].sum().sum()
    vaporization_state = {
        "1d_flow": system_momentum_1d,
        "5d_flow": system_momentum_5d,
        "is_vaporizing": system_momentum_5d < 0
    }

    # Transpose so rows are symbols and columns are dates for clustering
    # We want to cluster symbols based on their historical return patterns (Latent Topological Space)
    X = returns.T

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Use PCA to reduce dimensionality for clustering
    pca = PCA(n_components=min(10, len(X_scaled)))
    X_pca = pca.fit_transform(X_scaled)

    # KMeans Clustering to automatically group into continuous 'sectors'
    kmeans = KMeans(n_clusters=10, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(X_pca)

    learned_sectors = pd.Series(clusters, index=returns.columns, name='Learned_Sector')

    return learned_sectors, corr_matrix, vaporization_state

def generate_report(metrics, corr_matrix, vapor_state):
    """
    Generate a text-based analytical report summarized for hundreds of symbols.
    """
    print("\n" + "="*80)
    print("                 GLOBAL MACRO MARKET ANALYSIS REPORT")
    print("="*80)

    print("\n1. SECTOR CLUSTERING (Machine Learning Derived)")
    print("-" * 80)
    for cluster_id in sorted(metrics['Learned_Sector'].unique()):
        cluster_symbols = metrics[metrics['Learned_Sector'] == cluster_id].index.tolist()
        summary_symbols = cluster_symbols[:10]
        suffix = "..." if len(cluster_symbols) > 10 else ""
        print(f"Cluster {cluster_id} (Total {len(cluster_symbols)}): {', '.join(summary_symbols)}{suffix}")

    print("\n2. HIGH CORRELATION INFLUENCES (Major Benchmarks)")
    print("-" * 80)
    key_symbols = ["NVDA", "CL=F", "SPY", "TLT"]
    for sym in key_symbols:
        if sym in corr_matrix.columns:
            corrs = corr_matrix[sym].sort_values(ascending=False)
            top_pos = corrs[1:6]
            top_neg = corrs.tail(5)
            print(f"If {sym} moves, watch:")
            print(f"  Positively Correlated: {', '.join([f'{k} ({v:.2f})' for k, v in top_pos.items()])}")
            print(f"  Negatively Correlated: {', '.join([f'{k} ({v:.2f})' for k, v in top_neg.items()])}")
        else:
            print(f"Could not analyze influence for {sym} (data unavailable).")

    print("\n3. TOP EXTREME TRENDS (vs 50-Day SMA)")
    print("-" * 80)
    strong_bulls = metrics[(metrics['Dist_from_SMA_50_pct'] > 5) & (metrics['RSI_14'] < 70)].sort_values(by='Dist_from_SMA_50_pct', ascending=False).head(10)
    strong_bears = metrics[(metrics['Dist_from_SMA_50_pct'] < -5) & (metrics['RSI_14'] > 30)].sort_values(by='Dist_from_SMA_50_pct', ascending=True).head(10)

    print(f"Top 10 Bullish Trends (Price > 5% above SMA50, Not Overbought):")
    if not strong_bulls.empty:
        for idx, row in strong_bulls.iterrows():
            print(f"  {idx:5}: Current={row['Current_Price']:7.2f}, SMA50={row['SMA_50']:7.2f} (+{row['Dist_from_SMA_50_pct']:5.1f}%)")
    else:
        print("  None")

    print(f"\nTop 10 Bearish Trends (Price > 5% below SMA50, Not Oversold):")
    if not strong_bears.empty:
        for idx, row in strong_bears.iterrows():
            print(f"  {idx:5}: Current={row['Current_Price']:7.2f}, SMA50={row['SMA_50']:7.2f} ({row['Dist_from_SMA_50_pct']:5.1f}%)")
    else:
        print("  None")

    print("\n4. OVERBOUGHT/OVERSOLD ALERTS")
    print("-" * 80)
    overbought = metrics[metrics['RSI_Signal'] == 'Overbought'].index.tolist()
    oversold = metrics[metrics['RSI_Signal'] == 'Oversold'].index.tolist()

    print(f"Overbought (RSI > 70, Total {len(overbought)}): {', '.join(overbought[:10])}{'...' if len(overbought) > 10 else ''}")
    print(f"Oversold (RSI < 30, Total {len(oversold)}): {', '.join(oversold[:10])}{'...' if len(oversold) > 10 else ''}")


    print("\n5. CONTINUOUS WEALTH DIFFUSION & SYSTEMIC VAPORIZATION (dh/dt)")
    print("-" * 80)
    print(f"Systemic Liquidity State:")
    print(f"  1-Day Global Derivative Sum (dh/dt): {vapor_state['1d_flow']:7.2f}")
    print(f"  5-Day Global Derivative Sum (dh/dt): {vapor_state['5d_flow']:7.2f}")

    if vapor_state['is_vaporizing']:
        print("  => ALERT: SYSTEMIC VAPORIZATION DETECTED. Global macro liquidity is exiting the closed loop (Total dh/dt < 0).")
    else:
        print("  => STATUS: LIQUIDITY EXPANSION. Capital is actively flowing into the system (Total dh/dt > 0).")

    print("\n  Top Liquidity Sinks (Highest Inflow Velocity dh/dt 5d):")
    top_inflow = metrics.sort_values(by='dh_dt_5d', ascending=False).head(5)
    for idx, row in top_inflow.iterrows():
        print(f"    {idx:5}: {row['dh_dt_5d']*100:6.2f}%")

    print("\n  Top Liquidity Sources (Highest Outflow Velocity dh/dt 5d):")
    top_outflow = metrics.sort_values(by='dh_dt_5d', ascending=True).head(5)
    for idx, row in top_outflow.iterrows():
        print(f"    {idx:5}: {row['dh_dt_5d']*100:6.2f}%")

    print("="*80 + "\n")

if __name__ == "__main__":
    df = fetch_data(SYMBOLS)
    metrics = calculate_indicators(df)
    sectors, corr, vapor = perform_ml_analysis(df)
    metrics = metrics.join(sectors)
    generate_report(metrics, corr, vapor)
